name: english-learning
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - fastapi
    - uvicorn[standard]
    - sqlalchemy
    - pydantic[email]
    - python-jose[cryptography]
    - bcrypt
    - python-multipart
    - python-dotenv
    - pytest
    - httpx
